import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/ui/theme-provider'
import { ModeToggle } from '@/components/ui/mode-toggle'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <nav className='flex justify-between'>
          <h1 className='ml-7 md:ml-6'>
            Crypto Tracker
            {/* <ModeToggle/> */}
          </h1>
            <div className='ml-auto md:mr-6'>
            <ModeToggle/>
            </div>
        </nav>
        {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
